export const INDIA_CITY_AREAS = {
  Bengaluru: [
    'Indiranagar',
    'Koramangala',
    'Whitefield',
    'HSR Layout',
    'Jayanagar',
    'Electronic City',
    'Marathahalli',
    'BTM Layout',
    'Rajajinagar',
    'Yelahanka',
    'Hebbal',
    'Malleshwaram',
    'Banashankari',
    'Sarjapur Road',
    'Bellandur',
  ],
  Chennai: [
    'T Nagar',
    'Anna Nagar',
    'Velachery',
    'Adyar',
    'Tambaram',
    'OMR',
    'Porur',
    'Chromepet',
    'Mylapore',
    'Ambattur',
    'Thiruvanmiyur',
    'Perungudi',
    'Nungambakkam',
    'Kodambakkam',
    'Vadapalani',
  ],
  Delhi: [
    'Connaught Place',
    'Karol Bagh',
    'Dwarka',
    'Rohini',
    'Lajpat Nagar',
    'Saket',
    'Janakpuri',
    'Pitampura',
    'Vasant Kunj',
    'South Extension',
    'Mayur Vihar',
    'Rajouri Garden',
    'Chandni Chowk',
    'Preet Vihar',
    'Paschim Vihar',
  ],
  Gurgaon: [
    'DLF Phase 1',
    'DLF Phase 2',
    'DLF Phase 3',
    'DLF Phase 4',
    'DLF Phase 5',
    'Golf Course Road',
    'Golf Course Extension',
    'Sohna Road',
    'Sector 14',
    'Sector 29',
    'Sector 46',
    'Sector 56',
    'Sector 57',
    'Palam Vihar',
    'Udyog Vihar',
  ],
  Hyderabad: [
    'Banjara Hills',
    'Jubilee Hills',
    'Gachibowli',
    'Madhapur',
    'Kukatpally',
    'Hitech City',
    'Begumpet',
    'Ameerpet',
    'Miyapur',
    'Kondapur',
    'Secunderabad',
    'Manikonda',
    'Uppal',
    'LB Nagar',
    'Dilsukhnagar',
  ],
  Kolkata: [
    'Salt Lake',
    'New Town',
    'Park Street',
    'Howrah',
    'Dum Dum',
    'Garia',
    'Behala',
    'Ballygunge',
    'Jadavpur',
    'Tollygunge',
    'Esplanade',
    'Rajarhat',
    'Alipore',
    'Barasat',
    'Kasba',
  ],
  Mumbai: [
    'Andheri',
    'Bandra',
    'Powai',
    'Borivali',
    'Goregaon',
    'Malad',
    'Thane',
    'Navi Mumbai',
    'Dadar',
    'Chembur',
    'Lower Parel',
    'Colaba',
    'Kurla',
    'Vashi',
    'Mulund',
  ],
  Noida: [
    'Sector 18',
    'Sector 62',
    'Sector 63',
    'Sector 76',
    'Sector 78',
    'Sector 93',
    'Sector 104',
    'Sector 110',
    'Sector 137',
    'Sector 143',
    'Sector 150',
    'Noida Extension',
    'Greater Noida',
    'Pari Chowk',
    'Knowledge Park',
  ],
  Pune: [
    'Hinjewadi',
    'Kothrud',
    'Viman Nagar',
    'Hadapsar',
    'Wakad',
    'Baner',
    'Aundh',
    'Kharadi',
    'Magarpatta',
    'Pimpri',
    'Chinchwad',
    'Nigdi',
    'Shivajinagar',
    'Pimple Saudagar',
    'Koregaon Park',
  ],
  Ahmedabad: [
    'Satellite',
    'Navrangpura',
    'Prahlad Nagar',
    'Bopal',
    'Bodakdev',
    'Maninagar',
    'Chandkheda',
    'Naranpura',
    'Vastrapur',
    'Gota',
    'Thaltej',
    'CG Road',
    'Paldi',
    'Nikol',
    'Sabarmati',
  ],
  Jaipur: [
    'Malviya Nagar',
    'Vaishali Nagar',
    'Mansarovar',
    'Jagatpura',
    'C Scheme',
    'Raja Park',
    'Tonk Road',
    'Sodala',
    'Vidyadhar Nagar',
    'Jhotwara',
    'Bani Park',
    'Adarsh Nagar',
    'Sanganer',
    'Pratap Nagar',
    'Ajmer Road',
  ],
  Kochi: [
    'Kakkanad',
    'Edappally',
    'Palarivattom',
    'Fort Kochi',
    'Vyttila',
    'Kaloor',
    'Aluva',
    'Thrippunithura',
    'Marine Drive',
    'Angamaly',
    'Kadavanthra',
    'Panampilly Nagar',
    'Perumbavoor',
    'Mattancherry',
    'MG Road',
  ],
};

const AREA_NAME_ALIASES = {
  Bengaluru: {
    marathahalli: 'Marathahalli',
    marathalli: 'Marathahalli',
    marthahalli: 'Marathahalli',
    মারথাহাল্লি: 'Marathahalli',
    marthalli: 'Marathahalli',
  },
};

export const CITY_OPTIONS = Object.keys(INDIA_CITY_AREAS);
export const DEFAULT_CITY = CITY_OPTIONS[0];
export const AREAS = INDIA_CITY_AREAS[DEFAULT_CITY];

export const normalizeAreaName = (city, area) => {
  if (!area) return area;

  const directMatch = (INDIA_CITY_AREAS[city] || []).find(
    (candidate) => candidate.toLowerCase() === `${area}`.trim().toLowerCase()
  );

  if (directMatch) {
    return directMatch;
  }

  const aliasMap = AREA_NAME_ALIASES[city] || {};
  return aliasMap[`${area}`.trim().toLowerCase()] || area;
};

export const getAreasForCity = (city) =>
  INDIA_CITY_AREAS[city] || INDIA_CITY_AREAS[DEFAULT_CITY];

export const SERVICE_TYPES = [
  'Tyre puncture',
  'Battery issue',
  'Engine problem',
  'Oil leak',
  'General breakdown',
];

export const REQUEST_STATUS = {
  PENDING: 'Pending',
  ACCEPTED: 'Accepted',
  REJECTED: 'Rejected',
  COMPLETED: 'Completed',
};
